[project]
name = "photo-enhance-api"
version = "0.1.0"
description = "FastAPI + OpenCV + Pillow image enhancer"
authors = ["info5806"]
requires-python = ">=3.11"

dependencies = [
  "fastapi",
  "uvicorn",
  "opencv-python",
  "pillow",
  "python-multipart"
]
